# Leeky Configuration

# Data loader configuration
data_loader:
  batch_size: 100
  cache_enabled: False

# Test runner configuration
test_runner:
  batch_size: 10
  max_retries: 3
  timeout: 30.0
  sampling_strategy: "random"
  sampling_parameters:
    size: 10
  text_splitting:
    enabled: true
    strategy: "ratio"  # Options: ratio, sentence, paragraph
    split_ratio: 0.8     # Use 80% for context, 20% for completion comparison

# Engine configuration
engine:
  engine_type: "openai"
  parameters:
    temperature: 0.7
    max_tokens: 100
    model: "gpt-4"
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
